services:
  reverse-proxy:
    image: traefik:v3.6@sha256:e9ad2ada010742d2f91586a56f9ebb8355a2ceae7fb2973ef1c1877c7890e176
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80" # The HTTP port
      - "8081:8080" # The Web UI (enabled by --api.insecure=true)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # So that Traefik can listen to the Docker events

  watt-app:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.http.routers.watt-app.rule=Host(`watt-app.traefik.me`)"
      - "traefik.http.services.watt-app.loadbalancer.server.port=3042"
    environment:
      NODE_ENV: production
    command: npm run start